# Generated by Django 5.0.6 on 2025-08-22 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
