# Generated by Django 5.0.6 on 2025-08-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_invitation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='from_person',
            field=models.CharField(blank=True, choices=[('DIDIER', 'Didier'), ('MARI', 'Mari')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='group_person',
            field=models.CharField(blank=True, choices=[('FAMILY', 'Family'), ('FRIENDS', 'Friends')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='type',
            field=models.CharField(blank=True, choices=[('FAMILY', 'Family'), ('INDIVIDUAL', 'Individual')], max_length=255, null=True),
        ),
    ]
