# Generated by Django 5.0.6 on 2025-08-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0003_invitation_from_person_invitation_group_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='from_person',
            field=models.CharField(blank=True, choices=[('DIDIER', 'didier'), ('MARI', 'mari')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='group_person',
            field=models.CharField(blank=True, choices=[('FAMILY', 'family'), ('FRIENDS', 'friend')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='type',
            field=models.CharField(blank=True, choices=[('FAMILY', 'family'), ('INDIVIDUAL', 'individual')], max_length=255, null=True),
        ),
    ]
