# Generated by Django 5.0.6 on 2025-08-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_alter_invitation_from_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='from_person',
            field=models.CharField(blank=True, choices=[('DIDIER', 'DIDIER'), ('MARI', 'MARI')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='group_person',
            field=models.CharField(blank=True, choices=[('FAMILY', 'FAMILY'), ('FRIENDS', 'FRIENDS')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='type',
            field=models.CharField(blank=True, choices=[('FAMILY', 'FAMILY'), ('INDIVIDUAL', 'INDIVIDUAL')], max_length=255, null=True),
        ),
    ]
