# Generated by Django 5.0.6 on 2025-08-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0005_alter_invitation_from_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='type',
            field=models.CharField(blank=True, choices=[('GROUP', 'GROUP'), ('INDIVIDUAL', 'INDIVIDUAL')], max_length=255, null=True),
        ),
    ]
