# Generated by Django 5.0.6 on 2025-09-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_alter_person_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.FileField(null=True, upload_to='persons/photos/'),
        ),
    ]
