# Generated by Django 5.0.6 on 2025-09-25 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_person_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='photo',
        ),
    ]
