# Generated by Django 5.0.6 on 2025-12-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
